---

- name: 'Create Amazon VM Instance(s)'
  ec2:
    # set in vars/main.yml, just for convenience
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    zone: "{{ zone }}"
    image: "{{ ami }}"
    instance_tags: "{{ instance_tags }}"
    assign_public_ip: "{{ public_ip }}"
    vpc_subnet_id: "{{ subnet }}"
    group: "{{ group }}"
    count: 2
    monitoring: yes
    wait: yes
    state: present
    # passed as 'extra_vars' from BPM form input
    instance_type: "{{ instance_type }}"
  register: newmachines

- name: Wait for SSH to start
  wait_for:
    host: "{{ newmachines.instances[0].public_ip }}"
    port: 22
    timeout: 300
  delegate_to: localhost

- name: Record DNS name for email
  set_fact:
    ec2_dns_name: "{{ newmachines.instances[0].public_dns_name }}"
- debug: var=ec2_dns_name

- name: Add new VM to in memory inventory so we can post-process
  add_host:
    hostname: "{{ newmachines.instances[0].public_ip }}"
    groups: justcreatedlinux
#   ec2_dns_name: "{{ newmachines.instances[0].public_dns_name }}"
